version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
    timezone: Asia/Calcutta
  open-pull-requests-limit: 50
  ignore:
  - dependency-name: expo-font
    versions:
    - 8.1.0
    - 9.1.0
  - dependency-name: expo-asset
    versions:
    - 8.1.4
    - 8.2.2
    - 8.3.1
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: jest-expo
    versions:
    - 34.0.1
    - 40.0.2
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.0
    - 7.23.1
  - dependency-name: expo-file-system
    versions:
    - 10.0.0
  - dependency-name: "@expo/vector-icons"
    versions:
    - 12.0.3
  - dependency-name: lodash-es
    versions:
    - 4.17.20
  - dependency-name: redux-form
    versions:
    - 8.3.5
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: eslint-plugin-promise
    versions:
    - 4.2.1
  - dependency-name: redux
    versions:
    - 4.0.5
